targets:
  $default:
    builders:
      freezed|freezed:
        enabled: true
        generate_for:
          - lib/src/core/result/result.dart
          - lib/src/data/models/bluetooth_device_model.dart
          - lib/src/domain/entities/bluetooth_device_entity.dart
          - lib/src/presentation/blocs/bluetooth_connection/bluetooth_connection_bloc.dart
          - lib/src/presentation/blocs/bluetooth_devices/bluetooth_devices_bloc.dart
      mockito|mockBuilder:
        enabled: true
        generate_for:
          - test/data/dataSources/remote_data_source_test.dart
          - test/data/repositories/bluetooth_repository_test.dart
          - test/domain/useCases/start_bluetooth_devices_scan_test.dart
          - test/presentation/blocs/bluetooth_connection/bluetooth_connection_bloc_test.dart
          - test/presentation/blocs/bluetooth_devices/bluetooth_devices_bloc_test.dart
