name: ticket_printer
description: A Flutter project to manage ticket printer.
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  bluetooth_print: # Version ^4.2.0 has an error for image size
    git:
      url: git@github.com:YannMancel/bluetooth_print.git
      ref: fix-image-size-for-tsc-command
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  mockito: ^5.4.2

flutter:
