name: example
description: A Flutter project as example to use ticket_printer package.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  bluetooth_print: # Version ^4.2.0 has an error for image size
    git:
      url: git@github.com:YannMancel/bluetooth_print.git
      ref: fix-image-size-for-tsc-command
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  printing: ^5.11.0
  ticket_printer:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/etiquette_test.png
